// DO NOT EDIT
// Generated by JFlex 1.9.1 http://jflex.de/
// source: ruby.flex


@SuppressWarnings("fallthrough")
public final class RubyLexer {

  /** This character denotes the end of file. */
  public static final int YYEOF = -1;

  /** Initial size of the lookahead buffer. */
  private static final int ZZ_BUFFERSIZE = 16384;

  // Lexical states.
  public static final int YYINITIAL = 0;
  public static final int STRING = 2;

  /**
   * ZZ_LEXSTATE[l] is the state in the DFA for the lexical state l
   * ZZ_LEXSTATE[l+1] is the state in the DFA for the lexical state l
   *                  at the beginning of a line
   * l is of the form l = 2*k, k a non negative integer
   */
  private static final int ZZ_LEXSTATE[] = {
     0,  0,  1, 1
  };

  /**
   * Top-level table for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_TOP = zzUnpackcmap_top();

  private static final String ZZ_CMAP_TOP_PACKED_0 =
    "\1\0\37\u0100\1\u0200\267\u0100\10\u0300\u1020\u0100";

  private static int [] zzUnpackcmap_top() {
    int [] result = new int[4352];
    int offset = 0;
    offset = zzUnpackcmap_top(ZZ_CMAP_TOP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_top(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Second-level tables for translating characters to character classes
   */
  private static final int [] ZZ_CMAP_BLOCKS = zzUnpackcmap_blocks();

  private static final String ZZ_CMAP_BLOCKS_PACKED_0 =
    "\11\0\1\1\1\2\1\3\1\4\1\5\22\0\1\1"+
    "\1\6\1\7\1\10\1\11\2\12\1\0\1\13\1\14"+
    "\1\15\1\16\1\14\1\16\1\17\1\20\1\21\1\22"+
    "\2\23\4\24\2\25\2\14\1\26\1\27\1\30\1\31"+
    "\1\14\1\32\1\33\1\32\1\34\1\35\1\36\1\37"+
    "\1\40\1\41\1\42\1\40\1\43\1\40\1\44\11\40"+
    "\1\45\2\40\1\13\1\46\1\14\1\12\1\47\1\14"+
    "\1\50\1\51\1\52\1\53\1\54\1\55\1\56\1\57"+
    "\1\60\1\42\1\61\1\62\1\63\1\64\1\65\1\66"+
    "\1\40\1\67\1\70\1\71\1\72\1\40\1\73\1\74"+
    "\1\75\1\40\1\13\1\12\2\14\6\0\1\3\u01a2\0"+
    "\2\3\326\0\u0100\3";

  private static int [] zzUnpackcmap_blocks() {
    int [] result = new int[1024];
    int offset = 0;
    offset = zzUnpackcmap_blocks(ZZ_CMAP_BLOCKS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackcmap_blocks(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /**
   * Translates DFA states to action switch labels.
   */
  private static final int [] ZZ_ACTION = zzUnpackAction();

  private static final String ZZ_ACTION_PACKED_0 =
    "\2\0\1\1\3\2\1\1\1\3\1\4\1\1\1\5"+
    "\1\6\4\5\2\7\2\5\3\10\1\1\20\10\1\11"+
    "\1\12\1\1\2\4\1\13\5\7\1\0\2\7\1\0"+
    "\1\14\2\10\1\0\10\10\1\15\17\10\3\11\1\7"+
    "\1\0\3\7\1\10\2\0\6\10\1\15\16\10\2\7"+
    "\1\10\2\0\7\10\2\7\1\0\1\10\2\7\1\0"+
    "\2\7\1\0\2\7\1\16\5\7\1\0\1\7\1\0"+
    "\1\7\1\0\1\7\1\0\1\7\1\0\1\7\1\0"+
    "\1\7\1\0\1\7\1\0\4\7";

  private static int [] zzUnpackAction() {
    int [] result = new int[164];
    int offset = 0;
    offset = zzUnpackAction(ZZ_ACTION_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAction(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /**
   * Translates a state to a row index in the transition table
   */
  private static final int [] ZZ_ROWMAP = zzUnpackRowMap();

  private static final String ZZ_ROWMAP_PACKED_0 =
    "\0\0\0\76\0\174\0\272\0\174\0\370\0\u0136\0\174"+
    "\0\u0174\0\u01b2\0\u0136\0\174\0\174\0\u01f0\0\u022e\0\u026c"+
    "\0\u02aa\0\u02e8\0\u0326\0\u0364\0\u03a2\0\u03e0\0\u041e\0\u045c"+
    "\0\u049a\0\u04d8\0\u0516\0\u0554\0\u0592\0\u05d0\0\u060e\0\u064c"+
    "\0\u068a\0\u06c8\0\u0706\0\u0744\0\u0782\0\u07c0\0\u07fe\0\u083c"+
    "\0\u087a\0\174\0\u08b8\0\174\0\u08f6\0\u0934\0\u0972\0\u09b0"+
    "\0\u09ee\0\u0a2c\0\u0a6a\0\u0aa8\0\u0ae6\0\174\0\u0b24\0\174"+
    "\0\u0b62\0\u0ba0\0\u0bde\0\u0c1c\0\u0c5a\0\u0c98\0\u0cd6\0\u0d14"+
    "\0\u0d52\0\u0d90\0\u0dce\0\u03a2\0\u0e0c\0\u0e4a\0\u0e88\0\u0ec6"+
    "\0\u0f04\0\u0f42\0\u0f80\0\u0fbe\0\u0ffc\0\u103a\0\u1078\0\u10b6"+
    "\0\u10f4\0\u1132\0\u1170\0\174\0\u11ae\0\u11ec\0\u122a\0\u1268"+
    "\0\u12a6\0\u12e4\0\u1322\0\u1360\0\u139e\0\u13dc\0\u141a\0\u1458"+
    "\0\u1496\0\u14d4\0\u1512\0\u1550\0\u158e\0\u15cc\0\u160a\0\u1648"+
    "\0\u1686\0\u16c4\0\u1702\0\u1740\0\u177e\0\u17bc\0\u17fa\0\u1838"+
    "\0\u1876\0\u18b4\0\u18f2\0\u1930\0\u196e\0\u19ac\0\u19ea\0\u1a28"+
    "\0\u1a66\0\u1aa4\0\u1ae2\0\u1b20\0\u1b5e\0\u1b9c\0\u1bda\0\u1c18"+
    "\0\u1c56\0\u1c94\0\u1cd2\0\u1d10\0\u1d4e\0\u1d8c\0\u1dca\0\u1e08"+
    "\0\u1e46\0\u1e84\0\u1ec2\0\174\0\u1f00\0\u1f3e\0\u1f7c\0\u1fba"+
    "\0\u1ff8\0\u2036\0\u2074\0\u20b2\0\u20f0\0\u212e\0\u216c\0\u21aa"+
    "\0\u21e8\0\u2226\0\u2264\0\u22a2\0\u22e0\0\u231e\0\u235c\0\u239a"+
    "\0\u23d8\0\u2416\0\u2454\0\u2492";

  private static int [] zzUnpackRowMap() {
    int [] result = new int[164];
    int offset = 0;
    offset = zzUnpackRowMap(ZZ_ROWMAP_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackRowMap(String packed, int offset, int [] result) {
    int i = 0;  /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length() - 1;
    while (i < l) {
      int high = packed.charAt(i++) << 16;
      result[j++] = high | packed.charAt(i++);
    }
    return j;
  }

  /**
   * The transition table of the DFA
   */
  private static final int [] ZZ_TRANS = zzUnpacktrans();

  private static final String ZZ_TRANS_PACKED_0 =
    "\1\3\1\4\1\5\1\3\1\4\1\6\1\7\1\10"+
    "\1\11\1\12\1\13\1\14\1\15\1\16\1\13\1\17"+
    "\1\20\1\21\4\22\1\23\1\13\1\24\1\3\1\25"+
    "\1\26\1\25\1\27\10\25\1\3\1\30\1\31\1\32"+
    "\1\33\1\34\1\35\1\36\2\25\1\37\2\25\1\40"+
    "\1\41\1\42\1\25\1\43\1\44\1\45\1\46\1\47"+
    "\1\25\1\50\2\51\1\3\2\51\1\3\1\51\1\52"+
    "\36\51\1\53\27\51\77\0\1\4\2\0\1\4\73\0"+
    "\1\5\122\0\1\15\46\0\2\11\1\54\2\11\1\55"+
    "\70\11\32\0\14\56\2\0\26\56\15\0\1\13\11\0"+
    "\1\15\65\0\1\15\1\0\5\57\70\0\1\13\6\0"+
    "\1\15\65\0\1\57\1\0\1\60\1\61\2\62\1\63"+
    "\7\0\1\64\1\65\4\0\1\66\1\0\1\67\6\0"+
    "\1\64\1\65\4\0\1\66\11\0\1\67\20\0\1\57"+
    "\1\0\5\22\7\0\1\64\1\65\4\0\1\66\10\0"+
    "\1\64\1\65\4\0\1\66\41\0\1\13\2\15\74\0"+
    "\1\15\1\13\66\0\5\25\3\0\1\70\14\25\1\0"+
    "\27\25\21\0\5\25\3\0\1\70\3\25\1\71\10\25"+
    "\1\0\27\25\21\0\5\25\3\0\1\70\12\25\1\72"+
    "\1\25\1\0\27\25\47\0\1\73\47\0\5\25\3\0"+
    "\1\70\14\25\1\0\13\25\1\74\1\25\1\75\3\25"+
    "\1\76\5\25\21\0\5\25\3\0\1\70\14\25\1\0"+
    "\5\25\1\77\12\25\1\100\6\25\21\0\5\25\3\0"+
    "\1\70\14\25\1\0\1\25\1\101\11\25\1\102\13\25"+
    "\21\0\5\25\3\0\1\70\14\25\1\0\5\25\1\103"+
    "\10\25\1\104\10\25\21\0\5\25\3\0\1\70\14\25"+
    "\1\0\13\25\1\105\1\25\1\106\11\25\21\0\5\25"+
    "\3\0\1\70\14\25\1\0\1\25\1\107\14\25\1\42"+
    "\10\25\21\0\5\25\3\0\1\70\14\25\1\0\6\25"+
    "\1\104\6\25\1\104\11\25\21\0\5\25\3\0\1\70"+
    "\14\25\1\0\16\25\1\110\10\25\21\0\5\25\3\0"+
    "\1\70\14\25\1\0\5\25\1\111\3\25\1\112\4\25"+
    "\1\113\10\25\21\0\5\25\3\0\1\70\14\25\1\0"+
    "\20\25\1\104\6\25\21\0\5\25\3\0\1\70\14\25"+
    "\1\0\5\25\1\114\21\25\21\0\5\25\3\0\1\70"+
    "\14\25\1\0\5\25\1\115\15\25\1\116\3\25\21\0"+
    "\5\25\3\0\1\70\14\25\1\0\10\25\1\117\7\25"+
    "\1\120\6\25\21\0\5\25\3\0\1\70\14\25\1\0"+
    "\15\25\1\121\11\25\21\0\5\25\3\0\1\70\14\25"+
    "\1\0\10\25\1\122\16\25\21\0\5\25\3\0\1\70"+
    "\14\25\1\0\11\25\1\123\15\25\2\51\1\0\2\51"+
    "\1\0\1\51\1\0\36\51\1\0\27\51\2\124\4\0"+
    "\13\124\3\125\1\126\51\124\2\0\1\54\114\0\5\56"+
    "\4\0\14\56\1\0\27\56\21\0\5\57\7\0\1\64"+
    "\1\65\15\0\1\64\1\65\37\0\1\57\1\0\1\60"+
    "\1\61\2\62\1\63\7\0\1\64\1\65\4\0\1\66"+
    "\10\0\1\64\1\65\4\0\1\66\32\0\1\57\1\0"+
    "\4\62\1\63\7\0\1\64\1\65\4\0\1\66\10\0"+
    "\1\64\1\65\4\0\1\66\32\0\1\57\1\0\4\127"+
    "\1\63\7\0\1\64\1\65\4\0\1\66\10\0\1\64"+
    "\1\65\4\0\1\66\32\0\1\57\1\0\5\63\7\0"+
    "\1\64\1\65\15\0\1\64\1\65\36\0\1\130\2\0"+
    "\5\131\112\0\1\66\54\0\1\132\4\133\4\0\5\133"+
    "\11\0\6\133\41\0\5\25\3\0\1\70\5\25\1\134"+
    "\6\25\1\0\27\25\21\0\5\25\3\0\1\70\2\25"+
    "\1\104\11\25\1\0\27\25\36\0\1\135\4\0\1\136"+
    "\53\0\5\25\3\0\1\70\14\25\1\0\11\25\1\137"+
    "\15\25\21\0\5\25\3\0\1\70\14\25\1\0\4\25"+
    "\1\104\22\25\21\0\5\25\3\0\1\70\14\25\1\0"+
    "\21\25\1\140\5\25\21\0\5\25\3\0\1\70\14\25"+
    "\1\0\7\25\1\141\17\25\21\0\5\25\3\0\1\70"+
    "\14\25\1\0\5\25\1\142\21\25\21\0\5\25\3\0"+
    "\1\70\14\25\1\0\21\25\1\143\5\25\21\0\5\25"+
    "\3\0\1\70\14\25\1\0\1\25\1\144\25\25\21\0"+
    "\5\25\3\0\1\70\14\25\1\0\6\25\1\145\20\25"+
    "\21\0\5\25\3\0\1\70\14\25\1\0\21\25\1\146"+
    "\5\25\21\0\5\25\3\0\1\70\14\25\1\0\4\25"+
    "\1\104\14\25\1\147\5\25\21\0\5\25\3\0\1\70"+
    "\14\25\1\0\13\25\1\101\13\25\21\0\5\25\3\0"+
    "\1\70\14\25\1\0\4\25\1\150\22\25\21\0\5\25"+
    "\3\0\1\70\14\25\1\0\25\25\1\113\1\25\21\0"+
    "\5\25\3\0\1\70\14\25\1\0\13\25\1\104\13\25"+
    "\21\0\5\25\3\0\1\70\14\25\1\0\22\25\1\104"+
    "\4\25\21\0\5\25\3\0\1\70\14\25\1\0\4\25"+
    "\1\151\14\25\1\152\1\153\4\25\21\0\5\25\3\0"+
    "\1\70\14\25\1\0\13\25\1\154\13\25\21\0\5\25"+
    "\3\0\1\70\14\25\1\0\17\25\1\155\7\25\21\0"+
    "\5\25\3\0\1\70\14\25\1\0\5\25\1\156\21\25"+
    "\21\0\5\25\3\0\1\70\14\25\1\0\23\25\1\143"+
    "\3\25\21\0\5\25\3\0\1\70\14\25\1\0\4\25"+
    "\1\157\6\25\1\160\6\25\1\161\4\25\21\0\5\25"+
    "\3\0\1\70\14\25\1\0\5\25\1\156\3\25\1\162"+
    "\15\25\21\0\5\25\3\0\1\70\14\25\1\0\5\25"+
    "\1\163\21\25\21\0\4\126\72\0\4\124\70\0\1\57"+
    "\1\0\4\164\1\63\7\0\1\64\1\65\4\0\1\66"+
    "\10\0\1\64\1\65\4\0\1\66\34\0\5\131\71\0"+
    "\5\131\10\0\1\65\16\0\1\65\41\0\1\132\4\133"+
    "\4\0\5\133\4\0\1\66\4\0\6\133\4\0\1\66"+
    "\34\0\5\165\4\0\5\165\4\0\1\66\4\0\6\165"+
    "\4\0\1\66\34\0\5\25\3\0\1\70\7\25\1\166"+
    "\4\25\1\0\27\25\41\0\1\167\75\0\1\170\55\0"+
    "\5\25\3\0\1\70\14\25\1\0\1\25\1\171\25\25"+
    "\21\0\5\25\3\0\1\70\14\25\1\0\5\25\1\172"+
    "\21\25\21\0\5\25\3\0\1\70\14\25\1\0\11\25"+
    "\1\156\15\25\21\0\5\25\3\0\1\70\14\25\1\0"+
    "\1\25\1\173\25\25\21\0\5\25\3\0\1\70\14\25"+
    "\1\0\5\25\1\104\21\25\21\0\5\25\3\0\1\70"+
    "\14\25\1\0\21\25\1\171\5\25\21\0\5\25\3\0"+
    "\1\70\14\25\1\0\11\25\1\174\15\25\21\0\5\25"+
    "\3\0\1\70\14\25\1\0\5\25\1\104\3\25\1\154"+
    "\15\25\21\0\5\25\3\0\1\70\14\25\1\0\23\25"+
    "\1\175\3\25\21\0\5\25\3\0\1\70\14\25\1\0"+
    "\23\25\1\162\3\25\21\0\5\25\3\0\1\70\14\25"+
    "\1\0\16\25\1\104\10\25\21\0\5\25\3\0\1\70"+
    "\14\25\1\0\3\25\1\120\23\25\21\0\5\25\3\0"+
    "\1\70\14\25\1\0\20\25\1\176\2\25\1\177\3\25"+
    "\21\0\5\25\3\0\1\70\14\25\1\0\6\25\1\104"+
    "\20\25\21\0\5\25\3\0\1\70\14\25\1\0\5\25"+
    "\1\42\21\25\21\0\5\25\3\0\1\70\14\25\1\0"+
    "\15\25\1\104\11\25\21\0\5\25\3\0\1\70\14\25"+
    "\1\0\5\25\1\154\21\25\21\0\5\25\3\0\1\70"+
    "\14\25\1\0\5\25\1\144\21\25\21\0\5\25\3\0"+
    "\1\70\14\25\1\0\11\25\1\112\15\25\21\0\5\25"+
    "\3\0\1\70\14\25\1\0\13\25\1\143\13\25\21\0"+
    "\5\25\3\0\1\70\14\25\1\0\13\25\1\75\13\25"+
    "\17\0\1\57\1\0\4\200\1\63\7\0\1\64\1\65"+
    "\4\0\1\66\10\0\1\64\1\65\4\0\1\66\34\0"+
    "\5\201\4\0\5\201\4\0\1\66\4\0\6\201\4\0"+
    "\1\66\34\0\5\25\3\0\1\70\12\25\1\104\1\25"+
    "\1\0\27\25\43\0\1\202\76\0\1\202\52\0\5\25"+
    "\3\0\1\70\14\25\1\0\21\25\1\104\5\25\21\0"+
    "\5\25\3\0\1\70\14\25\1\0\20\25\1\113\6\25"+
    "\21\0\5\25\3\0\1\70\14\25\1\0\12\25\1\104"+
    "\14\25\21\0\5\25\3\0\1\70\14\25\1\0\15\25"+
    "\1\203\11\25\21\0\5\25\3\0\1\70\14\25\1\0"+
    "\20\25\1\143\6\25\21\0\5\25\3\0\1\70\14\25"+
    "\1\0\26\25\1\104\21\0\5\25\3\0\1\70\14\25"+
    "\1\0\20\25\1\156\6\25\17\0\1\57\1\0\4\204"+
    "\1\63\7\0\1\64\1\65\4\0\1\66\10\0\1\64"+
    "\1\65\4\0\1\66\34\0\5\205\4\0\5\205\4\0"+
    "\1\66\4\0\6\205\4\0\1\66\50\0\1\206\61\0"+
    "\5\25\3\0\1\70\14\25\1\0\5\25\1\75\21\25"+
    "\17\0\1\57\1\0\4\207\1\63\7\0\1\64\1\65"+
    "\4\0\1\66\10\0\1\64\1\65\4\0\1\66\34\0"+
    "\5\210\4\0\5\210\4\0\1\66\4\0\6\210\4\0"+
    "\1\66\62\0\1\211\45\0\1\57\1\0\4\212\1\63"+
    "\7\0\1\64\1\65\4\0\1\66\10\0\1\64\1\65"+
    "\4\0\1\66\34\0\5\213\4\0\5\213\4\0\1\66"+
    "\4\0\6\213\4\0\1\66\62\0\1\214\45\0\1\57"+
    "\1\0\4\215\1\63\7\0\1\64\1\65\4\0\1\66"+
    "\10\0\1\64\1\65\4\0\1\66\34\0\5\216\4\0"+
    "\5\216\4\0\1\66\4\0\6\216\4\0\1\66\32\0"+
    "\1\57\1\0\4\217\1\63\7\0\1\64\1\65\4\0"+
    "\1\66\10\0\1\64\1\65\4\0\1\66\34\0\5\220"+
    "\4\0\5\220\4\0\1\66\4\0\6\220\4\0\1\66"+
    "\32\0\1\57\1\0\4\221\1\63\7\0\1\64\1\65"+
    "\4\0\1\66\10\0\1\64\1\65\4\0\1\66\34\0"+
    "\5\222\4\0\5\222\4\0\1\66\4\0\6\222\4\0"+
    "\1\66\32\0\1\57\1\0\4\223\1\63\7\0\1\64"+
    "\1\65\4\0\1\66\10\0\1\64\1\65\4\0\1\66"+
    "\34\0\5\224\4\0\5\224\4\0\1\66\4\0\6\224"+
    "\4\0\1\66\32\0\1\57\1\0\4\225\1\63\7\0"+
    "\1\64\1\65\4\0\1\66\10\0\1\64\1\65\4\0"+
    "\1\66\34\0\5\226\4\0\5\226\4\0\1\66\4\0"+
    "\6\226\4\0\1\66\32\0\1\57\1\0\4\227\1\63"+
    "\7\0\1\64\1\65\4\0\1\66\10\0\1\64\1\65"+
    "\4\0\1\66\34\0\5\230\4\0\5\230\4\0\1\66"+
    "\4\0\6\230\4\0\1\66\32\0\1\57\1\0\4\231"+
    "\1\63\7\0\1\64\1\65\4\0\1\66\10\0\1\64"+
    "\1\65\4\0\1\66\34\0\5\232\4\0\5\232\4\0"+
    "\1\66\4\0\6\232\4\0\1\66\32\0\1\57\1\0"+
    "\4\233\1\63\7\0\1\64\1\65\4\0\1\66\10\0"+
    "\1\64\1\65\4\0\1\66\34\0\5\234\4\0\5\234"+
    "\4\0\1\66\4\0\6\234\4\0\1\66\32\0\1\57"+
    "\1\0\4\235\1\63\7\0\1\64\1\65\4\0\1\66"+
    "\10\0\1\64\1\65\4\0\1\66\34\0\5\236\4\0"+
    "\5\236\4\0\1\66\4\0\6\236\4\0\1\66\32\0"+
    "\1\57\1\0\4\237\1\63\7\0\1\64\1\65\4\0"+
    "\1\66\10\0\1\64\1\65\4\0\1\66\34\0\5\240"+
    "\4\0\5\240\4\0\1\66\4\0\6\240\4\0\1\66"+
    "\32\0\1\57\1\0\4\241\1\63\7\0\1\64\1\65"+
    "\4\0\1\66\10\0\1\64\1\65\4\0\1\66\56\0"+
    "\1\66\16\0\1\66\32\0\1\57\1\0\4\242\1\63"+
    "\7\0\1\64\1\65\4\0\1\66\10\0\1\64\1\65"+
    "\4\0\1\66\32\0\1\57\1\0\4\243\1\63\7\0"+
    "\1\64\1\65\4\0\1\66\10\0\1\64\1\65\4\0"+
    "\1\66\32\0\1\57\1\0\4\244\1\63\7\0\1\64"+
    "\1\65\4\0\1\66\10\0\1\64\1\65\4\0\1\66"+
    "\32\0\1\57\1\0\5\63\7\0\1\64\1\65\4\0"+
    "\1\66\10\0\1\64\1\65\4\0\1\66\13\0";

  private static int [] zzUnpacktrans() {
    int [] result = new int[9424];
    int offset = 0;
    offset = zzUnpacktrans(ZZ_TRANS_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpacktrans(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      value--;
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }


  /** Error code for "Unknown internal scanner error". */
  private static final int ZZ_UNKNOWN_ERROR = 0;
  /** Error code for "could not match input". */
  private static final int ZZ_NO_MATCH = 1;
  /** Error code for "pushback value was too large". */
  private static final int ZZ_PUSHBACK_2BIG = 2;

  /**
   * Error messages for {@link #ZZ_UNKNOWN_ERROR}, {@link #ZZ_NO_MATCH}, and
   * {@link #ZZ_PUSHBACK_2BIG} respectively.
   */
  private static final String ZZ_ERROR_MSG[] = {
    "Unknown internal scanner error",
    "Error: could not match input",
    "Error: pushback value was too large"
  };

  /**
   * ZZ_ATTRIBUTE[aState] contains the attributes of state {@code aState}
   */
  private static final int [] ZZ_ATTRIBUTE = zzUnpackAttribute();

  private static final String ZZ_ATTRIBUTE_PACKED_0 =
    "\2\0\1\11\1\1\1\11\2\1\1\11\3\1\2\11"+
    "\34\1\1\11\1\1\1\11\7\1\1\0\1\1\1\11"+
    "\1\0\1\11\2\1\1\0\30\1\1\11\3\1\1\0"+
    "\4\1\2\0\30\1\2\0\11\1\1\0\3\1\1\0"+
    "\2\1\1\0\2\1\1\11\5\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\1\1\1\0\1\1\1\0"+
    "\1\1\1\0\1\1\1\0\4\1";

  private static int [] zzUnpackAttribute() {
    int [] result = new int[164];
    int offset = 0;
    offset = zzUnpackAttribute(ZZ_ATTRIBUTE_PACKED_0, offset, result);
    return result;
  }

  private static int zzUnpackAttribute(String packed, int offset, int [] result) {
    int i = 0;       /* index in packed string  */
    int j = offset;  /* index in unpacked array */
    int l = packed.length();
    while (i < l) {
      int count = packed.charAt(i++);
      int value = packed.charAt(i++);
      do result[j++] = value; while (--count > 0);
    }
    return j;
  }

  /** Input device. */
  private java.io.Reader zzReader;

  /** Current state of the DFA. */
  private int zzState;

  /** Current lexical state. */
  private int zzLexicalState = YYINITIAL;

  /**
   * This buffer contains the current text to be matched and is the source of the {@link #yytext()}
   * string.
   */
  private char zzBuffer[] = new char[Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen())];

  /** Text position at the last accepting state. */
  private int zzMarkedPos;

  /** Current text position in the buffer. */
  private int zzCurrentPos;

  /** Marks the beginning of the {@link #yytext()} string in the buffer. */
  private int zzStartRead;

  /** Marks the last character in the buffer, that has been read from input. */
  private int zzEndRead;

  /**
   * Whether the scanner is at the end of file.
   * @see #yyatEOF
   */
  private boolean zzAtEOF;

  /**
   * The number of occupied positions in {@link #zzBuffer} beyond {@link #zzEndRead}.
   *
   * <p>When a lead/high surrogate has been read from the input stream into the final
   * {@link #zzBuffer} position, this will have a value of 1; otherwise, it will have a value of 0.
   */
  private int zzFinalHighSurrogate = 0;

  /** Number of newlines encountered up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yyline;

  /** Number of characters from the last newline up to the start of the matched text. */
  @SuppressWarnings("unused")
  private int yycolumn;

  /** Number of characters up to the start of the matched text. */
  private long yychar;

  /** Whether the scanner is currently at the beginning of a line. */
  @SuppressWarnings("unused")
  private boolean zzAtBOL = true;

  /** Whether the user-EOF-code has already been executed. */
  @SuppressWarnings("unused")
  private boolean zzEOFDone;

  /* user code: */
    // to store string literal
    StringBuffer string = new StringBuffer();


  /**
   * Creates a new scanner
   *
   * @param   in  the java.io.Reader to read input from.
   */
  public RubyLexer(java.io.Reader in) {
    this.zzReader = in;
  }


  /** Returns the maximum size of the scanner buffer, which limits the size of tokens. */
  private int zzMaxBufferLen() {
    return Integer.MAX_VALUE;
  }

  /**  Whether the scanner buffer can grow to accommodate a larger token. */
  private boolean zzCanGrow() {
    return true;
  }

  /**
   * Translates raw input code points to DFA table row
   */
  private static int zzCMap(int input) {
    int offset = input & 255;
    return offset == input ? ZZ_CMAP_BLOCKS[offset] : ZZ_CMAP_BLOCKS[ZZ_CMAP_TOP[input >> 8] | offset];
  }

  /**
   * Refills the input buffer.
   *
   * @return {@code false} iff there was new input.
   * @exception java.io.IOException  if any I/O-Error occurs
   */
  private boolean zzRefill() throws java.io.IOException {

    /* first: make room (if you can) */
    if (zzStartRead > 0) {
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
      System.arraycopy(zzBuffer, zzStartRead,
                       zzBuffer, 0,
                       zzEndRead - zzStartRead);

      /* translate stored positions */
      zzEndRead -= zzStartRead;
      zzCurrentPos -= zzStartRead;
      zzMarkedPos -= zzStartRead;
      zzStartRead = 0;
    }

    /* is the buffer big enough? */
    if (zzCurrentPos >= zzBuffer.length - zzFinalHighSurrogate && zzCanGrow()) {
      /* if not, and it can grow: blow it up */
      char newBuffer[] = new char[Math.min(zzBuffer.length * 2, zzMaxBufferLen())];
      System.arraycopy(zzBuffer, 0, newBuffer, 0, zzBuffer.length);
      zzBuffer = newBuffer;
      zzEndRead += zzFinalHighSurrogate;
      zzFinalHighSurrogate = 0;
    }

    /* fill the buffer with new input */
    int requested = zzBuffer.length - zzEndRead;
    int numRead = zzReader.read(zzBuffer, zzEndRead, requested);

    /* not supposed to occur according to specification of java.io.Reader */
    if (numRead == 0) {
      if (requested == 0) {
        throw new java.io.EOFException("Scan buffer limit reached ["+zzBuffer.length+"]");
      }
      else {
        throw new java.io.IOException(
            "Reader returned 0 characters. See JFlex examples/zero-reader for a workaround.");
      }
    }
    if (numRead > 0) {
      zzEndRead += numRead;
      if (Character.isHighSurrogate(zzBuffer[zzEndRead - 1])) {
        if (numRead == requested) { // We requested too few chars to encode a full Unicode character
          --zzEndRead;
          zzFinalHighSurrogate = 1;
        } else {                    // There is room in the buffer for at least one more char
          int c = zzReader.read();  // Expecting to read a paired low surrogate char
          if (c == -1) {
            return true;
          } else {
            zzBuffer[zzEndRead++] = (char)c;
          }
        }
      }
      /* potentially more input available */
      return false;
    }

    /* numRead < 0 ==> end of stream */
    return true;
  }


  /**
   * Closes the input reader.
   *
   * @throws java.io.IOException if the reader could not be closed.
   */
  public final void yyclose() throws java.io.IOException {
    zzAtEOF = true; // indicate end of file
    zzEndRead = zzStartRead; // invalidate buffer

    if (zzReader != null) {
      zzReader.close();
    }
  }


  /**
   * Resets the scanner to read from a new input stream.
   *
   * <p>Does not close the old reader.
   *
   * <p>All internal variables are reset, the old input stream <b>cannot</b> be reused (internal
   * buffer is discarded and lost). Lexical state is set to {@code ZZ_INITIAL}.
   *
   * <p>Internal scan buffer is resized down to its initial length, if it has grown.
   *
   * @param reader The new input stream.
   */
  public final void yyreset(java.io.Reader reader) {
    zzReader = reader;
    zzEOFDone = false;
    yyResetPosition();
    zzLexicalState = YYINITIAL;
    int initBufferSize = Math.min(ZZ_BUFFERSIZE, zzMaxBufferLen());
    if (zzBuffer.length > initBufferSize) {
      zzBuffer = new char[initBufferSize];
    }
  }

  /**
   * Resets the input position.
   */
  private final void yyResetPosition() {
      zzAtBOL  = true;
      zzAtEOF  = false;
      zzCurrentPos = 0;
      zzMarkedPos = 0;
      zzStartRead = 0;
      zzEndRead = 0;
      zzFinalHighSurrogate = 0;
      yyline = 0;
      yycolumn = 0;
      yychar = 0L;
  }


  /**
   * Returns whether the scanner has reached the end of the reader it reads from.
   *
   * @return whether the scanner has reached EOF.
   */
  public final boolean yyatEOF() {
    return zzAtEOF;
  }


  /**
   * Returns the current lexical state.
   *
   * @return the current lexical state.
   */
  public final int yystate() {
    return zzLexicalState;
  }


  /**
   * Enters a new lexical state.
   *
   * @param newState the new lexical state
   */
  public final void yybegin(int newState) {
    zzLexicalState = newState;
  }


  /**
   * Returns the text matched by the current regular expression.
   *
   * @return the matched text.
   */
  public final String yytext() {
    return new String(zzBuffer, zzStartRead, zzMarkedPos-zzStartRead);
  }


  /**
   * Returns the character at the given position from the matched text.
   *
   * <p>It is equivalent to {@code yytext().charAt(pos)}, but faster.
   *
   * @param position the position of the character to fetch. A value from 0 to {@code yylength()-1}.
   *
   * @return the character at {@code position}.
   */
  public final char yycharat(int position) {
    return zzBuffer[zzStartRead + position];
  }


  /**
   * How many characters were matched.
   *
   * @return the length of the matched text region.
   */
  public final int yylength() {
    return zzMarkedPos-zzStartRead;
  }


  /**
   * Reports an error that occurred while scanning.
   *
   * <p>In a well-formed scanner (no or only correct usage of {@code yypushback(int)} and a
   * match-all fallback rule) this method will only be called with things that
   * "Can't Possibly Happen".
   *
   * <p>If this method is called, something is seriously wrong (e.g. a JFlex bug producing a faulty
   * scanner etc.).
   *
   * <p>Usual syntax/scanner level error handling should be done in error fallback rules.
   *
   * @param errorCode the code of the error message to display.
   */
  private static void zzScanError(int errorCode) {
    String message;
    try {
      message = ZZ_ERROR_MSG[errorCode];
    } catch (ArrayIndexOutOfBoundsException e) {
      message = ZZ_ERROR_MSG[ZZ_UNKNOWN_ERROR];
    }

    throw new Error(message);
  }


  /**
   * Pushes the specified amount of characters back into the input stream.
   *
   * <p>They will be read again by then next call of the scanning method.
   *
   * @param number the number of characters to be read again. This number must not be greater than
   *     {@link #yylength()}.
   */
  public void yypushback(int number)  {
    if ( number > yylength() )
      zzScanError(ZZ_PUSHBACK_2BIG);

    zzMarkedPos -= number;
  }




  /**
   * Resumes scanning until the next regular expression is matched, the end of input is encountered
   * or an I/O-Error occurs.
   *
   * @return the next token.
   * @exception java.io.IOException if any I/O-Error occurs.
   */
  public Token yylex() throws java.io.IOException
  {
    int zzInput;
    int zzAction;

    // cached fields:
    int zzCurrentPosL;
    int zzMarkedPosL;
    int zzEndReadL = zzEndRead;
    char[] zzBufferL = zzBuffer;

    int [] zzTransL = ZZ_TRANS;
    int [] zzRowMapL = ZZ_ROWMAP;
    int [] zzAttrL = ZZ_ATTRIBUTE;

    while (true) {
      zzMarkedPosL = zzMarkedPos;

      yychar+= zzMarkedPosL-zzStartRead;

      zzAction = -1;

      zzCurrentPosL = zzCurrentPos = zzStartRead = zzMarkedPosL;

      zzState = ZZ_LEXSTATE[zzLexicalState];

      // set up zzAction for empty match case:
      int zzAttributes = zzAttrL[zzState];
      if ( (zzAttributes & 1) == 1 ) {
        zzAction = zzState;
      }


      zzForAction: {
        while (true) {

          if (zzCurrentPosL < zzEndReadL) {
            zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
            zzCurrentPosL += Character.charCount(zzInput);
          }
          else if (zzAtEOF) {
            zzInput = YYEOF;
            break zzForAction;
          }
          else {
            // store back cached positions
            zzCurrentPos  = zzCurrentPosL;
            zzMarkedPos   = zzMarkedPosL;
            boolean eof = zzRefill();
            // get translated positions and possibly new buffer
            zzCurrentPosL  = zzCurrentPos;
            zzMarkedPosL   = zzMarkedPos;
            zzBufferL      = zzBuffer;
            zzEndReadL     = zzEndRead;
            if (eof) {
              zzInput = YYEOF;
              break zzForAction;
            }
            else {
              zzInput = Character.codePointAt(zzBufferL, zzCurrentPosL, zzEndReadL);
              zzCurrentPosL += Character.charCount(zzInput);
            }
          }
          int zzNext = zzTransL[ zzRowMapL[zzState] + zzCMap(zzInput) ];
          if (zzNext == -1) break zzForAction;
          zzState = zzNext;

          zzAttributes = zzAttrL[zzState];
          if ( (zzAttributes & 1) == 1 ) {
            zzAction = zzState;
            zzMarkedPosL = zzCurrentPosL;
            if ( (zzAttributes & 8) == 8 ) break zzForAction;
          }

        }
      }

      // store back cached position
      zzMarkedPos = zzMarkedPosL;

      if (zzInput == YYEOF && zzStartRead == zzCurrentPos) {
        zzAtEOF = true;
              {
                return new Token(TokenType.EOF);
              }
      }
      else {
        switch (zzAction < 0 ? zzAction : ZZ_ACTION[zzAction]) {
          case 1:
            { throw new Error("Illegal character <" + yytext() + "<");
            }
          // fall through
          case 15: break;
          case 2:
            { 
            }
          // fall through
          case 16: break;
          case 3:
            { yybegin(STRING);
                                    string.setLength(0);
            }
          // fall through
          case 17: break;
          case 4:
            { return new Token(TokenType.COMMENT, yytext());
            }
          // fall through
          case 18: break;
          case 5:
            { return new Token(TokenType.OPERATOR, yytext());
            }
          // fall through
          case 19: break;
          case 6:
            { return new Token(TokenType.OPERATOR,  yytext());
            }
          // fall through
          case 20: break;
          case 7:
            { return new Token(TokenType.NUMBER, yytext());
            }
          // fall through
          case 21: break;
          case 8:
            { return new Token(TokenType.IDENTIFIER, yytext());
            }
          // fall through
          case 22: break;
          case 9:
            { string.append(yytext());
            }
          // fall through
          case 23: break;
          case 10:
            { yybegin(YYINITIAL); 
                                     // length also includes the trailing quote
                                     return new Token(TokenType.STRING, string.toString());
            }
          // fall through
          case 24: break;
          case 11:
            { return new Token(TokenType.GLOBALIDENTIFIER, yytext());
            }
          // fall through
          case 25: break;
          case 12:
            { return new Token(TokenType.TYPE2, yytext());
            }
          // fall through
          case 26: break;
          case 13:
            { return new Token(TokenType.KEYWORD, yytext());
            }
          // fall through
          case 27: break;
          case 14:
            { return new Token(TokenType.TYPE, yytext());
            }
          // fall through
          case 28: break;
          default:
            zzScanError(ZZ_NO_MATCH);
        }
      }
    }
  }


}
